### ISSUE TITLE
[update-job] (IntegrityError) duplicate key value violates unique constraint "projects_versions_pkey"

### ISSUE THREAD

**Issue by msrb** [bkabrda/anitya-docker#15]
```
[anitya DEBUG] Project gitv is already up to date.
[anitya INFO] Checking feed for backend <class 'anitya.lib.backends.sourceforge.SourceforgeBackend'>
[anitya DEBUG] Skipping feed check for backend <class 'anitya.lib.backends.sourceforge.SourceforgeBackend'>
[anitya INFO] Checking feed for backend <class 'anitya.lib.backends.stackage.StackageBackend'>
[anitya DEBUG] Skipping feed check for backend <class 'anitya.lib.backends.stackage.StackageBackend'>
[anitya INFO] Launching pool (10) to update 30 projects
[fedmsg.crypto.x509 WARNING] Crypto disabled ImportError('No module named M2Crypto',)
[anitya ERROR] 'getpwuid(): uid not found: 1002320000'
Traceback (most recent call last):
  File "/src/files/anitya_cron.py", line 123, in <module>
    main(debug=debug, feed=feed, by_ecosystem=by_ecosystem)
  File "/src/files/anitya_cron.py", line 112, in main
    p.map(update_project, project_ids)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
sqlalchemy.exc.IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) duplicate key value violates unique constraint "projects_versions_pkey"
DETAIL:  Key (project_id, version)=(12051, 1.2.0) already exists.
 'INSERT INTO projects_versions (project_id, version) VALUES (%(project_id)s, %(version)s)' {'project_id': 12051, 'version': u'1.2.0'}
[anitya ERROR] 'getpwuid(): uid not found: 1002320000'
[anitya ERROR] 'getpwuid(): uid not found: 1002320000'
Unhandled exception in thread started by <bound method DummyProcess.__bootstrap of <DummyProcess(Thread-2, stopped daemon 140673521673984)>>
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 824, in __bootstrap_inner
    (self.name, _format_exc()))
  File "/usr/lib64/python2.7/traceback.py", line 240, in format_exc
    + sleep 60
+ :
+ python /src/files/anitya_cron.py --check-feed --by-ecosystem
[anitya INFO] Checking feed for backend <class 'anitya.lib.backends.bitbucket.BitBucketBackend'>
```

**Comment by pkajaba** [comment]
It seems to be like some problem within a code, I am looking into this one.
